version: '3.7'
services:
    api-service:
        build: 
            context: ./api/
            dockerfile: Dockerfile
        image: trobify-api
        container_name: trobify-api-server
        volumes: 
            - ./api/:/usr/src/app/
        ports: 
            - 5000:5000
        depends_on:
            - db-service
        networks:
            - trobify-network
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            BD_CONN: mongodb://db-service:27017/
            DB_NAME: db-trobify
    db-service:
        image: mongo
        volumes:
        - data-volume:/data/db
        ports:
        - "27017:27017"
        networks:
        - trobify-network
    web-service:
        build:
            context: ./web/
            dockerfile: Dockerfile
        environment:
            - CHOKIDAR_USEPOLLING=true
        image: trobify-client
        container_name: trobify-web-client
        stdin_open: true
        command: npm start
        volumes:
        - ./web/:/usr/app
        - /usr/app/node_modules
        depends_on:
        - api-service
        ports:
        - "3000:3000"
        networks:
        - trobify-network
        environment: 
            REACT_APP_API: http://localhost:5000/api/

networks:
    trobify-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local